CREATE DATABASE [NavTechProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NavTechProject', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\NavTechProject.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NavTechProject_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\NavTechProject_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [NavTechProject] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NavTechProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NavTechProject] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NavTechProject] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NavTechProject] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NavTechProject] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NavTechProject] SET ARITHABORT OFF 
GO
ALTER DATABASE [NavTechProject] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NavTechProject] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NavTechProject] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NavTechProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NavTechProject] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NavTechProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NavTechProject] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NavTechProject] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NavTechProject] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NavTechProject] SET  DISABLE_BROKER 
GO
ALTER DATABASE [NavTechProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NavTechProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NavTechProject] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NavTechProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NavTechProject] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NavTechProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NavTechProject] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NavTechProject] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [NavTechProject] SET  MULTI_USER 
GO
ALTER DATABASE [NavTechProject] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NavTechProject] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NavTechProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NavTechProject] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [NavTechProject] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [NavTechProject] SET  READ_WRITE 
GO
